---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
- token: ${JOIN_TOKEN}
  description: kubeadm bootstrap token
localAPIEndpoint:
  advertiseAddress: ${HOST_IP}
  bindPort: 6443
certificateKey: ${CERTIFICATE_KEY}
nodeRegistration:
  name: ${NODE_NAME}
  kubeletExtraArgs:
    node-ip: ${HOST_IP}
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.22.4
clusterName: ${CLUSTER_NAME}
controlPlaneEndpoint: ${CONTROL_PLANE_LOAD_BALANCER}:6443
networking:
  dnsDomain: cluster.local
  podSubnet: ${POD_SUBNET}
  serviceSubnet: ${SERVICE_SUBNET}
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
